server.port=38024

spring.application.name=receipt-service

spring.datasource.url=jdbc:postgresql://localhost:5435/hos_receipt
spring.datasource.username=postgres
spring.datasource.password=Admin@0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:3802/eureka/

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-in-ms=86400000
app.jwt.token.prefix=Bearer 
app.jwt.header.string=Authorization
